### PR TITLE
TEX directive parsing

### PR DESCRIPTION
**Pull request by ig0774**
This adds `%!TEX` directive parsing and code to modify the build command based on the selected program or options (NB I've only eye-balled the texify code; I don't use MiKTeX too frequently).

Part of the changes enable `get_tex_root` to take a TextEditor instance and return the root from that directly.

### CODE REVIEW

**Comment by msiniscalchi** [comment]
Thanks @ig0774 ! I merged this code. I also moved the tex log parser and the bib file parser to the `parsers` directory, as that seems logical, and added some tweaks for the texify code.

BTW there is a slight difference with the ST version. There, we use `%!TEX option` rather than `%!TEX options`. Maybe we should accept both, or else standardize on one---but people on ST have been using `option`, and I don't want to break things for them. On the other hand I don't want to complicate the code just for the sake of backwards compatibility with a different platform... I need to sleep over this!

**Comment by msiniscalchi** [comment]
Two things @ig0774 : 

1. There were a couple of subtle bugs related to tex directives. First, Coffeescript's named parameters are a thin coat of paint over Javascript. In particular, even if you name parameters, you *must* still pass them in the same order as in the function definition! Also, to pass named parameters you must use "=" and not ":". [I am figuring things out by trial and error; documentation is not Python-like, sadly...]

2. I decided to opt for the following convention: each `%!TEX option = " line must have a single option; however, the user can use multiple such lines. Note that it's `option` and not `optionS`. I just think it's cleaner that way, and it's also consistent with the ST version of the plugin.

**Comment by ig0774** [comment]
@msiniscalchi: Not that I mind you making whatever changes you think appropriate, but (hey, since we're both learning):

1. The limitations you describe pretty much why I didn't just use straight-forward Coffeescript named parameters. Actually, all arguments in Javascript are (kind of) optional, in so far as names are bound in the order that arguments are passed in, which isn't always convenient when you want to provide an API that *can* take some parameters but doesn't need to. One way this is worked around in pure JS is, instead of providing a list of arguments, providing an object that can contain keys pointing to what the arguments should be if they are given at all. It looks something like this:

```javascript
function (requiredArgs, opts) {
     opts ||= {};
     optionalArgument = opts.optionalArgument || defaultValue;
}
```

The `{multiValues, keyMaps} = {}` syntax does basically the same thing as the javascript above, it relies not on passed-in arguments named `multiValues` or `keyMaps`, but an object containing properties named either `multiValues` or `keyMaps`. The function body thus had some code to ensure these values were initialised and when its invoked. This syntax that requires a single object rather than actual optional arguments, which is what allows (and actually *requires*) using the `multiValue: ...` syntax to invoke it because, in Coffeescript, this implicitly creates an object with a `multiValue` property. In short, the syntax I used provides a way of working around needing named parameters to be in the same order or even specified at all, but it does so at the expense of slightly more LOC (to ensure the value is initialised).

2. Re: `options` that was a stupid typo on my part. Thanks for fixing that.

**Comment by msiniscalchi** [comment]
@ig0774 thanks, and I didn't mean to tamper with your code... I was just trying out different things. I am learning JS and CS at the same time, and the docs for CS are not very thorough, so the mapping is not immediately obvious (to me). 

The issue was that something was failing---the tex directive parsing code never actually picked up multiple parameters: if I had two lines such as

  %!TEX options = --opt1
  %!TEX options = -opt2

only `--opt2` would be returned. I think I tracked this down to the fact that `multiValues` and `keyMaps` were passed in the wrong order. 

However, this is not the whole story. I now understand that, by using `:` instead of `=`, you were trying to pass an object rather than named parameters---very neat! However, I guess the issue is how CS translates a call such as

  myFunction x:1, y:2

I guess the idea would be that you are passing an object with keys x and y. However, that's probably not what happens. I guess you would need curly braces to make sure:

  myFunction {x:1, y:2}

Thanks---M

**Pull request closed without merging**
