### PR TITLE
Resizable Console

### LINKED ISSUE #30: Increase size of LaTeXTools console panel
Is there a way to increase the size of the LaTeXTools console panel? The information in the console, especially the list of errors and warnings, is extremely useful but I can see only 3 lines at at a time. Seeing more lines would be very helpful.

### PR DESCRIPTION
**Pull request by ig0774**
The main intention is to fix #30 by making the LaTeXTools console resizable.

There is a functional change as it is now harder to append text to an existing line (it wouldn't be impossible to do, but I haven't implemented that feature here), which means I've dropped the `br` optional argument.

I also modestly changed how the console is styled. It's now using CSS properties, which has the advantage that the console can be styled any way the user likes using their own style-sheet.

In addition, `addContent` now uses the built-in error and warning colours, so errors and warnings should stand out a bit more in the log.

I think `atom-message-panel` is lightweight enough to be worth considering. It's main dependency is `space-pen`, which the plugin already uses.

### CODE REVIEW

**Comment by msiniscalchi** [comment]
This is great, thanks @ig0774 ! My only concern is that I was actually planning to remove the dependency on atom-space-pen, in the hope of speeding up the ref/cite panel. It's also a pretty hefty requirement, as it pulls in jQuery (I think). Actually, that was the main reason space-pen was removed from atom-core.

**Comment by msiniscalchi** [comment]
...though I have to say, this looks very beautiful!

**Comment by ig0774** [comment]
@msiniscalchi: It turned out to be not so difficult to convert this over to a completely space pen-free solution that I'm actually happier with, which is now what this PR is.

Re the ref / cite panel, isn't most of the delay due to using the `onDidStopChanging` event? At least on my (non-slow) computer, the delay seems to be the 300ms delay. If I turn off the complete-as-you-type bit and just use the key binding it seems to be almost instantaneous. But maybe I'm missing something?

**Comment by msiniscalchi** [comment]
Awesome!!!! Merged. I noticed there is an issue with jumping to errors/warnings, but I'll look into it. 

It **does** look very spiffy!

**Comment by msiniscalchi** [comment]
OK, don't have time right now, but there is a somewhat serious issue: jumping to warnings/errors doesn't work. With `texlive`, when I click on a warning/error, a new file is opened. The reason is that `texlive`'s tex log uses *relative* paths to tex files. This is what gets passed to `atom.workspace.open`.

In the new code, this happens in `LTConsoleMessaveView::gotoMessage`. In the previous code, this happened directly in the builder code. I *think* that the reason things worked there is that, before running `latexmk` or `texify`, we `chdir` to the directory containing the tex (root) file. Then, `atom.workspace.open` interprets paths as being relative to that, and everything works. [In particular, since the callback was given to `addContent` using `=>`, everything happened in the scope of the builder code, so the current  directory was indeed set correctly.]   In the new code instead the binding happens elsewhere, and the current directory is set to `.atom/latextools`. Indeed, if I have an error in a file called `file.tex`, the file that Atom tries to open is `.../.atom/latextools/file.tex`.

It's a subtle bug. Unless I am missing something, I am afraid the only fix is to pass the directory of the tex master file in the call to `addContent`, which is somewhat unsightly.

That said, I do love the new look!

**Comment by msiniscalchi** [comment]
Well, I fixed it (I think) by passing the dir.

**Comment by ig0774** [comment]
That's bizarre. I was a bit worried about passing the relative path just because of such things but it worked for me, so I didn't really dwell on it.

Something that might be midly cleaner is to create the absolute path in the builder and pass that to the console as the file (the file parameter is just used to create the clickable link; the text itself is separate), but either way it works. Now I'm stuck wondering what about my setup makes things different. Oh well.

**Comment by msiniscalchi** [comment]
Oh... I didn't notice that the message was a separate argument---mine was a really quick fix done before running to a seminar... 

Then the right thing to do is definitely to pass the full path as the file parameter. Actually, separating the file name and absolute path would be useful to support the option to put output (or auxiliary) files in a separate directory, which is something many users on Sublime Text have asked for.

BTW, miktex uses absolute paths in error logs. Also, there may be differences across different texlive versions---I"m using the 2014 version (I think). THis may explain why you didn't see it on your machine.

**Comment by msiniscalchi** [comment]
Pushed the change.

**Comment by msiniscalchi** [comment]
...and Win32 required another fix. Actually, the issue was that, if we have absolute paths, we must *not* prepend the directory. Hope it all works now!

**Pull request merged**
